slam_toolbox:
  ros__parameters:
    use_sim_time: true
    slam_toolbox_mode: "sync"

    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_footprint"   # or "base_link" if that is your odom child
    scan_topic: "scan"

    resolution: 0.05
    max_laser_range: 15.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

